### ISSUE TITLE
快速体验

### ISSUE THREAD

**Issue by mfuuzy** [kubecube-io/kubecube-io.github.io#27]
问题一：
在填写了Secrets 后，Deployment部署的时候，选择Secrets，会一直报错。
使用YAML的方式填写Secrets可以部署成功。
问题二：
我一直调不通Ingress 这部分，如果你们有实战部署的文档链接，可以给我贴一份吗，非常感谢。

**Comment by zhujf1989** [comment]
//cc @JiahuiZhao11

**Comment by JiahuiZhao11** [comment]
问题一：可以复制下具体的报错信息吗？ 
问题二：Ingress部分存在bug，会在下一版本修复，十分抱歉耽误了您的时间。具体的实战文档，已经在 #33 中更新，您可以用文档中的镜像部署，待下一版本发布后，按照文档操作即可。
